apiVersion: v1
kind: Pod
metadata:
  name: nginx-server
  labels:
    app: nginx-server
spec:
  containers:
    - name: nginx-test1
      image: nginx:1.19.4
      resources:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
          

