apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment 
  namespace: default 
  labels:
    app: nginx-server 
spec:
  strategy:
    type: Recreate 
  replicas: 3 
  selector:
    matchLabels:
      app: nginx-server 
  template: 
    metadata:
      labels: 
        app: nginx-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.19.4
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "100m"
